## Step 1: load data and clean missing values

In [ ]:
from google.colab import drive
drive.mount('/drive')

Mounted at /drive


In [ ]:
import pandas as pd
from numpy import nan
import numpy as np
data = pd.read_csv("/drive/My Drive/Colab Notebooks/data/CCST Survey_20221109_Text_Answers.csv")

In [ ]:
data=data[['myslice.satisfied','myslice.feedback']].copy()
display(data)

myslice.satisfied                                   myslice.feedback
0                Agree                                                NaN
1             Disagree                                                NaN
2                Agree                                                NaN
3                Agree                                                NaN
4                Agree                                                NaN
...                ...                                                ...
1718    Somewhat agree                                                NaN
1719          Disagree  Nothing is where I want it to be in MySlice. E...
1720    Strongly agree                                                NaN
1721    Somewhat agree  The credit card reconciliation process is horr...
1722    Somewhat agree                                                NaN

[1723 rows x 2 columns]

In [ ]:
data=data.dropna()
display(data)

myslice.satisfied                                   myslice.feedback
6                 Agree  Clearer directions, help contact information, ...
17                Agree  Can be difficult to navigate when trying to fi...
19    Strongly disagree  The platform switch to icons rather than heade...
24                Agree  I'd really like the option to set the default ...
34       Somewhat agree  I do not find Myslice as intuitive to use as i...
...                 ...                                                ...
1673     Somewhat agree  I am not always 100 percent clear on where to ...
1703           Disagree  The lack of support in many areas of myslice w...
1714     Strongly agree  PLEASEEEEEEEEEE   dont' change it!!!  I just g...
1719           Disagree  Nothing is where I want it to be in MySlice. E...
1721     Somewhat agree  The credit card reconciliation process is horr...

[480 rows x 2 columns]

export as CSV files as headers

In [ ]:
data.to_csv("myslice-calssification.csv")

#Set up the stop words list

In [ ]:
my_stopwords=frozenset(['might', 'take', 'ourselves', 'by', 'everything', 'therein', 'twenty', 'others', 'keep', 'ever', 'my', 'been', 'top',  'via', 'are', 'onto', 'would', 'most', 'rather', 'except', 'should', 'per', 'wherein', 'third', 'yourselves', 'nine', 'is', 'namely', 'besides',  'down', 'anyone', 'within', 'latter', 'whose', 'bill', 'throughout', 'until', 'former', 'anything', 'i', 'call', 'thru', 'put', 'see', 'meanwhile', 'very', 'whoever', 'somehow', 'she', 'hereby', 'beside', 'full', 'then', 'something', 'whether', 'can', 'me', 'wherever', 'yours', 'towards', 'together', 'upon', 'name', 'again', 'therefore', 'alone', 'between', 'whom', 'the', 'interest', 'done', 'hereupon', 'them', 'than', 'con', 'eg', 'these', 'becoming', 'much', 'beforehand', 'under', 'too', 'another', 'whither', 'ie', 'un', 'and', 'above', 'amongst', 'across', 'moreover', 'own', 'both', 'other', 'hers', 'find', 'was', 'an', 'many', 'de', 'indeed', 'three', 'twelve', 'serious', 'otherwise', 'thick', 'latterly', 'they', 'thin', 'whatever', 'how', 'same', 'anyway', 'once', 'herself', 'will', 'well', 'give', 'being', 'thereafter', 'seemed', 'sometimes', 'up', 'empty', 'fifteen', 'thereupon', 'where', 'co', 'from', 'whereas', 'over', 'am', 'itself', 'somewhere', 'along', 'which', 'forty', 'also', 'as', 'for', 'amoungst', 'after', 'of', 'back', 'thereby', 'it', 'detail', 'front', 're', 'us', 'five', 'such', 'whole', 'almost', 'made', 'their', 'mine', 'at', 'may', 'sixty', 'before', 'must', 'everywhere', 'amount', 'first', 'already', 'etc', 'eight', 'through', 'perhaps', 'several', 'that', 'mill', 'more', 'whence', 'due', 'each', 'themselves', 'become', 'seems', 'cry', 'into', 'still', 'your', 'why', 'sometime', 'some', 'whenever', 'please', 'neither', 'because', 'herein', 'has', 'this', 'among', 'during', 'when', 'one', 'there', 'ltd', 'hence', 'becomes', 'whereby', 'inc', 'everyone', 'last', 'against', 'out', 'he', 'move', 'all', 'now', 'either', 'bottom', 'nevertheless', 'fifty', 'side', 'hundred', 'his', 'so', 'else', 'or', 'were', 'you', 'further', 'yet', 'here', 'had', 'beyond', 'if', 'part', 'below', 'who', 'be', 'around', 'someone', 'whereupon', 'behind', 'seem', 'ten', 'enough', 'four', 'about', 'in', 'off', 'though', 'since', 'elsewhere', 'anywhere', 'myself', 'sincere', 'hereafter', 'system', 'on', 'ours', 'could', 'with', 'seeming', 'get', 'thence', 'two', 'always', 'toward', 'a', 'yourself', 'do', 'himself', 'her', 'next', 'have', 'mostly', 'formerly', 'we', 'eleven', 'found', 'whereafter', 'anyhow', 'became', 'thus', 'what', 'fire', 'describe', 'him', 'those', 'to', 'afterwards', 'even', 'every', 'fill',  'often', 'its', 'our', 'show', 'go', 'six'])
print(len(my_stopwords))

295


## Step 2: Split the data into training data and test data by 30%

In [ ]:
y=data['myslice.satisfied'].values
X=data['myslice.feedback'].values

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1337)

print(X_train.shape, y_train.shape, X_test.shape, y_test.shape)
print(X_train[0])
print(y_train[0])
print(X_test[0])
print(y_test[0])

(336,) (336,) (144,) (144,)
We have too many platforms that do not integrate with MySlice and it's always like pulling teeth to find what it is I am looking for. When I finally learn where something is--it changes and little communication goes out to inform us of these changes.
Strongly disagree
I'm not sure it is organized in a logical fashion.
Agree


In [ ]:
# Check if the dataset is balanced(the number of training examples in each category)
unique, counts = np.unique(y_train, return_counts=True)
print(np.asarray((unique, counts)))

[['Agree' 'Disagree' 'Somewhat agree' 'Somewhat disagree'
  'Strongly agree' 'Strongly disagree']
 [110 37 108 36 21 24]]


## Step 3: vectorization(unigram)

## Step 3.1.1: vectorize the training data(unigram)

In [ ]:
# Read the sklearn documentation to understand all vectorization options
from sklearn.feature_extraction.text import CountVectorizer
#  unigram term frequency vectorizer, set minimum document frequency to 5
unigram_count_vectorizer = CountVectorizer(encoding='latin-1', binary=False, min_df=2, stop_words='english')

In [ ]:
# fit vocabulary in training documents and transform the training documents into vectors
X_train_vec_uni = unigram_count_vectorizer.fit_transform(X_train)

# check the content of a document vector
print(X_train_vec_uni.shape)
print(X_train_vec_uni[0].toarray())

# check the size of the constructed vocabulary
print(len(unigram_count_vectorizer.vocabulary_))

# print out the first 10 items in the vocabulary
print(list(unigram_count_vectorizer.vocabulary_.items())[:10])

(336, 607)
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
  1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0

#Step 3.1.2: vectorize the test data(unigram)

In [ ]:
# use the vocabulary constructed from the training data to vectorize the test data. 
# Therefore, use "transform" only, not "fit_transform", 
X_test_vec_uni = unigram_count_vectorizer.transform(X_test)

# print out #examples and #features in the test set
print(X_test_vec_uni.shape)

(144, 607)


# Step 4: Train a MNB classifier

In [ ]:
# import the MNB module
from sklearn.naive_bayes import MultinomialNB

# initialize the MNB model
nb_clf= MultinomialNB()

# use the training data to train the MNB model
nb_clf.fit(X_train_vec_uni,y_train)

MultinomialNB()

# Step 4.1: Interpratation

In [ ]:
print(nb_clf.feature_log_prob_.shape)

# Step 4.2: Log ratio of conditional probabilities

In [ ]:
log_ratios = []
features = unigram_count_vectorizer.get_feature_names_out()
neg_cond_prob = nb_clf.feature_log_prob_[0]
pos_cond_prob = nb_clf.feature_log_prob_[1]

for i in range(0, len(features)):
  log_ratio = pos_cond_prob[i] - neg_cond_prob[i]
  log_ratios.append(log_ratio)

exercise_C_ranks = sorted(zip(log_ratios, features))
print(exercise_C_ranks[:10])#negative
print(exercise_C_ranks[-10:])#positive

[(-1.6791133055116978, 'changes'), (-1.5613302698553149, 'think'), (-1.5613302698553149, 'updates'), (-1.4967917487177438, 'information'), (-1.4277988772307921, 'bit'), (-1.4277988772307921, 'easier'), (-1.4277988772307921, 'email'), (-1.4277988772307921, 'usually'), (-1.2736481974035332, 'contact'), (-1.2736481974035332, 'didn')]
[(1.6167235604926313, 'slow'), (1.6167235604926313, 'speed'), (1.6167235604926313, 'tried'), (1.7708742403198894, 'make'), (1.7708742403198894, 'tile'), (1.9044056329444121, 'feels'), (1.9044056329444121, 'modern'), (1.9044056329444121, 'request'), (1.9044056329444121, 'stale'), (2.127549184258622, 'error')]


## Step 5: Test the MNB Classifier

In [ ]:
# test the classifier on the test data set, print accuracy score
nb_clf.score(X_test_vec_uni,y_test)

0.3680555555555556

In [ ]:
# print confusion matrix (row: ground truth; col: prediction)
from sklearn.metrics import confusion_matrix
y_pred = nb_clf.fit(X_train_vec_uni, y_train).predict(X_test_vec_uni)
cm=confusion_matrix(y_test, y_pred)
print(cm)

[[24  0 14  0  1  0]
 [ 8  3  5  2  0  3]
 [16  1 25  2  0  1]
 [ 7  3  7  1  0  0]
 [ 2  0  6  0  0  0]
 [ 4  2  6  1  0  0]]


In [ ]:
# print classification report

from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
print(precision_score(y_test, y_pred, average=None))
print(recall_score(y_test, y_pred, average=None))

from sklearn.metrics import classification_report
target_names = ['n','p']
print(classification_report(y_test, y_pred))

[0.39344262 0.33333333 0.3968254  0.16666667 0.         0.        ]
[0.61538462 0.14285714 0.55555556 0.05555556 0.         0.        ]
                   precision    recall  f1-score   support

            Agree       0.39      0.62      0.48        39
         Disagree       0.33      0.14      0.20        21
   Somewhat agree       0.40      0.56      0.46        45
Somewhat disagree       0.17      0.06      0.08        18
   Strongly agree       0.00      0.00      0.00         8
Strongly disagree       0.00      0.00      0.00        13

         accuracy                           0.37       144
        macro avg       0.22      0.23      0.20       144
     weighted avg       0.30      0.37      0.31       144



# Step 5.1: interpratation of results

In [ ]:
## find the calculated posterior probability
posterior_probs = nb_clf.predict_proba(X_test_vec_uni)

## find the posterior probabilities for the first test example
print(posterior_probs[0])

# find the category prediction for the first test example
y_pred = nb_clf.predict(X_test_vec_uni)
print(y_pred[0])

# check the actual label for the first test example
print(y_test[0])
print(X[0])

[0.11557292 0.03652326 0.45335254 0.29372849 0.04235276 0.05847004]
Somewhat agree
Agree
Clearer directions, help contact information, and info in Answers would be helpful


# Step 5.2: Error Analysis

In [ ]:
# print out specific type of error for further analysis

# print out the very positive examples that are mistakenly predicted as negative
# according to the confusion matrix, there should be 53 such examples
# note if you use a different vectorizer option, your result might be different

err_cnt = 0
for i in range(0, len(y_test)):
    if(y_test[i]=='Agree' and y_pred[i]=='Disagree'):
        print(X_test[i])
        err_cnt = err_cnt+1
print("Agree to Disagree errors:", err_cnt)

err_cnt = 0
for i in range(0, len(y_test)):
    if(y_test[i]=='Disagree' and y_pred[i]=='Agree'):
        print(X_test[i])
        err_cnt = err_cnt+1
print("Disagree to Agree errors:", err_cnt)

n to p errors: 0
Constantly getting timed out is frustrating as is switching from the Myslice student home page to the employee home page every time I sign on. The search function is good as there are a couple of things I can't figure out where they live.  Credit card reconciliation is nice that its all online and has a work flow but completing the form takes so much longer. Perhaps its a connectivity problem that I have to wait for every field of a chart string line.  At least in JPMC I could have a list of favorite chart string to choose from that would immediately populate the form.  I know ITS assists with Blackboard but as for Myslice I didn't know about help or support.  The role out of the new Myslice was terrible. Some prior communication could has softened the transition some (maybe).
Cumbersome, confusing, not user friendly, hard to find what I need, archaic 
There are many features controlled by multiple institutions such as HR or the registrar and not ITS, so ITS often repl

# Cross Validation

In [ ]:
from sklearn.naive_bayes import BernoulliNB
from sklearn.naive_bayes import MultinomialNB

from sklearn.pipeline import Pipeline
from sklearn.model_selection import cross_val_score
#unigram
nb_clf_pipe = Pipeline([('vect',  CountVectorizer(encoding='latin-1', binary=False)),('nb', MultinomialNB())])
scores = cross_val_score(nb_clf_pipe, X, y, cv=5)
avg=sum(scores)/len(scores)
print("unigram",avg)

#  boolean vectorizer
nb_clf_pipe = Pipeline([('vect', CountVectorizer(encoding='latin-1', binary=True)),('nb', MultinomialNB())])
scores = cross_val_score(nb_clf_pipe, X, y, cv=5)
avg=sum(scores)/len(scores)
print("unigram",avg)

#Bigram
nb_clf_pipe = Pipeline([('vect', CountVectorizer(encoding='latin-1', ngram_range=(2,2))),('nb', MultinomialNB())])
scores = cross_val_score(nb_clf_pipe, X, y, cv=5)
avg=sum(scores)/len(scores)
print("bigram",avg)

#  unigram and bigram 
nb_clf_pipe = Pipeline([('vect',CountVectorizer(encoding='latin-1', ngram_range=(1,2))),('nb', MultinomialNB())])
scores = cross_val_score(nb_clf_pipe, X, y, cv=5)
avg=sum(scores)/len(scores)
print("unigram and bigram",avg)

#  unigram tfidf vectorizer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import cross_val_score
nb_clf_pipe = Pipeline([('vect', TfidfVectorizer(encoding='latin-1', use_idf=True)),('nb', MultinomialNB())])
scores = cross_val_score(nb_clf_pipe, X, y, cv=5)
avg=sum(scores)/len(scores)
print("tf-idf",avg)

#TF-IDF

In [ ]:
#  TF-IDF term frequency vectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_count_vectorizer = TfidfVectorizer(encoding='latin-1', ngram_range=(1,2), analyzer= 'word', token_pattern=r"(?u)\b\w\w+\b|!|\?|\"|\'", stop_words=my_stopwords)

In [ ]:
# fit vocabulary in training documents and transform the training documents into vectors
X_train_vec_tf = tfidf_count_vectorizer.fit_transform(X_train)

# check the content of a document vector
print(X_train_vec_tf.shape)
print(X_train_vec_tf[0].toarray())

# check the size of the constructed vocabulary
print(len(tfidf_count_vectorizer.vocabulary_))

# print out the first 10 items in the vocabulary
print(list(tfidf_count_vectorizer.vocabulary_.items())[:10])

(336, 5571)
[[0. 0. 0. ... 0. 0. 0.]]
5571
[('platforms', 3801), ('not', 3326), ('integrate', 2379), ('myslice', 3008), ("'", 50), ('like', 2635), ('pulling', 3971), ('teeth', 4830), ('looking', 2809), ('finally', 1763)]


In [ ]:
# use the vocabulary constructed from the training data to vectorize the test data. 
# Therefore, use "transform" only, not "fit_transform", 
X_test_vec_tf = tfidf_count_vectorizer.transform(X_test)

# print out #examples and #features in the test set
print(X_test_vec_tf.shape)

(144, 5571)


#train MNB classifiers

In [ ]:
# import the MNB module
from sklearn.naive_bayes import MultinomialNB

# initialize the MNB model
nb_clf= MultinomialNB()

# use the training data to train the MNB model
nb_clf.fit(X_train_vec_tf,y_train)

MultinomialNB()

In [ ]:
print(nb_clf.feature_log_prob_.shape)

(6, 5571)


In [ ]:
log_ratios = []
features = tfidf_count_vectorizer.get_feature_names_out()
neg_cond_prob = nb_clf.feature_log_prob_[5]
pos_cond_prob = nb_clf.feature_log_prob_[4]

for i in range(0, len(features)):
  log_ratio = pos_cond_prob[i] - neg_cond_prob[i]
  log_ratios.append(log_ratio)

exercise_C_ranks = sorted(zip(log_ratios, features))
print(exercise_C_ranks[:10])#negative
print(exercise_C_ranks[-10:])#positive

[(-0.643850657041277, 'not'), (-0.5599592112054168, 'awful'), (-0.4716235974393115, 'update'), (-0.4402571632802772, 'change'), (-0.3983560426519954, 'available help'), (-0.3983560426519954, 'nobody'), (-0.3983560426519954, 'nobody available'), (-0.3974113491893405, 'not user'), (-0.3973673859033955, 'awful update'), (-0.3973673859033955, 'update change')]
[(0.4750062651138407, 'comment'), (0.4866188361707966, 'program'), (0.5009637692845619, 'nothing comment'), (0.5130776075755676, 'good program'), (0.5161658771126625, 'no issues'), (0.5587132787021396, 'work good'), (0.6989069210838377, 'good'), (0.7044044519590393, 'none'), (0.8503257393583699, 'great'), (0.923116212555307, 'works')]


# test under MNB classifier

In [ ]:
# test the classifier on the test data set, print accuracy score
nb_clf.score(X_test_vec_tf,y_test)

0.3680555555555556

In [ ]:
# print confusion matrix (row: ground truth; col: prediction)
from sklearn.metrics import confusion_matrix
y_pred = nb_clf.fit(X_train_vec_tf, y_train).predict(X_test_vec_tf)
cm=confusion_matrix(y_test, y_pred)
print(cm)

[[27  0 12  0  0  0]
 [10  0 11  0  0  0]
 [19  0 26  0  0  0]
 [10  0  8  0  0  0]
 [ 1  0  7  0  0  0]
 [ 6  0  7  0  0  0]]


In [ ]:
# print classification report

from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
print(precision_score(y_test, y_pred, average=None))
print(recall_score(y_test, y_pred, average=None))

from sklearn.metrics import classification_report
target_names = ['n','p']
print(classification_report(y_test, y_pred))

[0.36986301 0.         0.36619718 0.         0.         0.        ]
[0.69230769 0.         0.57777778 0.         0.         0.        ]
                   precision    recall  f1-score   support

            Agree       0.37      0.69      0.48        39
         Disagree       0.00      0.00      0.00        21
   Somewhat agree       0.37      0.58      0.45        45
Somewhat disagree       0.00      0.00      0.00        18
   Strongly agree       0.00      0.00      0.00         8
Strongly disagree       0.00      0.00      0.00        13

         accuracy                           0.37       144
        macro avg       0.12      0.21      0.16       144
     weighted avg       0.21      0.37      0.27       144



/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.8/dist-packages/sklearn/metrics/_classification.py:1318: 